### ISSUE TITLE
APIM Action - Fails to parse swagger on certain definitions

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/LogicAppsUX#1809]
### Describe the Bug

When adding a connection I am seeing the following console error when attempting to hit "create new"
```
SyntaxError: Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//dummy/post/responses/200
    Expected type string but found type null at #/paths//dummy/post/responses/200/description
    Missing required property: $ref at #/paths//dummy/post/responses/200

JSON_OBJECT_VALIDATION_FAILED
    at Function.n [as syntax] (https://afd.hosting-ms.portal.azure.net/ema/Content/Dynamic/tZPlOqUjxEoK.js:105:9447)
    at e.exports (https://afd.hosting-ms.portal.azure.net/ema/Content/Dynamic/tZPlOqUjxEoK.js:123:3254)
    at p.validate (https://afd.hosting-ms.portal.azure.net/ema/Content/Dynamic/tZPlOqUjxEoK.js:125:635167)

 

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at m.getLastError (https://afd.hosting-ms.portal.azure.net/ema/Content/Dynamic/tZPlOqUjxEoK.js:133:4358)
    at e.exports (https://afd.hosting-ms.portal.azure.net/ema/Content/Dynamic/tZPlOqUjxEoK.js:123:3028)
    at p.validate (https://afd.hosting-ms.portal.azure.net/ema/Content/Dynamic/tZPlOqUjxEoK.js:125:635167)
onError

       [Microsoft_Azure_EMA]  3:22:52 PM create connection tab Failed to create connection: SyntaxError: Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//dummy/post/responses/200
    Expected type string but found type null at #/paths//dummy/post/responses/200/description
    Missing required property: $ref at #/paths//dummy/post/responses/200

JSON_OBJECT_VALIDATION_FAILED {error: {…}} {resourceID: '/subscriptions/80d4fe69-c95b-4dd2-a938-9250f1c8ab0…UAlkarche-APIM/workflows/StatefulAPIMDesignerTest', designerVersion: '0.2.85', designerID: '309F4C94-AE81-4EBB-9DB3-3DCC2DB9C6E9'}
```

### Steps to Reproduce the Bug or Issue

In our LogicApps-PM subscription I have a site with the correct bundle to reproduce this issue. In "March2ndRUAlkarche-APMI" attempt to create a connection to "alkarche-standard-APIM" and the "dummyapi" api.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/22549328/227660809-cda8b35c-0e54-4980-bded-be13f27b656d.png">

### Workflow JSON

```json
This is the swagger from APIM that is generating the failure:

{
  "swagger": "2.0",
  "info": {
    "title": "DummyAPI",
    "version": "1.0"
  },
  "host": "alkarche-standard-apim.azure-api.net",
  "basePath": "/dummy",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "apiKeyHeader": {
      "type": "apiKey",
      "name": "Ocp-Apim-Subscription-Key",
      "in": "header"
    },
    "apiKeyQuery": {
      "type": "apiKey",
      "name": "subscription-key",
      "in": "query"
    }
  },
  "security": [
    {
      "apiKeyHeader": []
    },
    {
      "apiKeyQuery": []
    }
  ],
  "paths": {
    "/dummy": {
      "post": {
        "operationId": "dummy",
        "summary": "Dummy",
        "responses": {
          "200": {
            "description": null
          }
        }
      }
    }
  },
  "tags": []
}
```

### Expected behavior

I expect the API connection to create successfully.

### Platform And Browser

- OS: Windows 11
- Browser: Edge
- Version:  111.0.1661.43 (Official build) (64-bit)

**Comment by alexkarcher-msft** [comment]
I figured out what's going wrong with this. The definition I'm using doesn't have any responses defined. All of our examples have responses defined. This is valid swagger supported by APIM, so we should be able to parse that definition.

**Comment by alexkarcher-msft** [comment]
It looks like this issue is the result of invalid swaggers that are not supported by logic apps. I'd like to update this to instead request an error message be shown in the portal informing the user that their swagger is invalid. Today the UX displays nothing and the "save" button appears to do nothing. Errors are only shown in the browser console.
