### ISSUE TITLE
500 - InternalServerError while saving the map

### ISSUE THREAD

**Issue by shailesh-agre** [Azure/LogicAppsUX#1822]
### Describe the Bug

I am not able to save a very simple map – with just one element each on either side. 
Getting 500 InternalServer error.
I am using extension v2.0.8
I have verified that simple workflow runs fine locally.
Functions extension is 4.x
 
![image](https://user-images.githubusercontent.com/61179796/228335076-679632a0-7197-43e2-9a4b-b149684843c4.png)

Workflow-designtime – host.json
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
    "workflow": {
      "settings": {
        "Runtime.WorkflowOperationDiscoveryHostMode": "true"
      }
    }
  }
}
Workflow-Designtime - local.setting.json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsSecretStorageType": "Files",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "ProjectDirectoryPath": "c:\\temp1\\LASTDM",
    "Workflows.WebhookRedirectHostUri": https://4276-117-254-35-77.in.ngrok.io,
    "AzureWebJobsFeatureFlags": "EnableMultiLanguageWorker"
  }
}

### Steps to Reproduce the Bug or Issue

1. Create new map.
2. Add source and destination schema - very simple 1 element only.
3. link the elements and try to save the map and it throws the below error
4. In this scenario, yml file is not getting generated – Map folder is empty.

Data Mapper extension is loaded
Running command: "func host start --port 8000"...

Azure Functions Core Tools
Core Tools Version:       4.0.5085 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.16.4.20366

[2023-03-25T20:09:43.813Z] Csproj not found in c:\Beta\DataMapper\workflow-designtime directory tree. Skipping user secrets file configuration.

Functions:

    XsltNetFxLanguageWorkerFunction: NetFxTrigger

For detailed output, run func with --verbose flag.
[2023-03-25T20:09:47.358Z] Worker process started and initialized.
[2023-03-25T20:09:51.378Z] Host lock lease acquired by instance ID '0000000000000000000000001F24A23E'.
[2023-03-25T20:10:18.876Z] Error message: correlationId='bca417a8-cb3c-43e0-adf2-6a5fccd7c4c1', operationName='POST/RUNTIME/WORKFLOW/MANAGEMENT/', message='Http request failed with unhandled exception of type 'NullReferenceException' and message: 'System.NullReferenceException: Object reference not set to an instance of an object.
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.DataMapper.XsltCompiler.MapXsltGenerator..ctor(MapObjectModel map, FlowConfiguration flowConfiguration, String schemaArtifactFolder)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Data.Utilities.DataMapper.DataMapperUtility.GenerateXslt(FlowConfiguration flowConfiguration, String mapContent)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Controllers.EdgeMapDesignerApiController.GenerateXslt(CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.FlowExtensionRouteInitializer.Invoke(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionHttpRequestHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionAuthorizationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionErrorResponseHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)'.', exception='System.NullReferenceException: Object reference not set to an instance of an object.
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.DataMapper.XsltCompiler.MapXsltGenerator..ctor(MapObjectModel map, FlowConfiguration flowConfiguration, String schemaArtifactFolder)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Data.Utilities.DataMapper.DataMapperUtility.GenerateXslt(FlowConfiguration flowConfiguration, String mapContent)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Controllers.EdgeMapDesignerApiController.GenerateXslt(CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.FlowExtensionRouteInitializer.Invoke(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionHttpRequestHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionAuthorizationHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-03-25T20:10:18.876Z]    at Microsoft.Azure.Workflows.Web.Handlers.FlowExtensionErrorResponseHandler.HandleRequest(HttpRequestMessage request, CancellationToken cancellationToken)', organizationId='', activityVector='IN.00', additionalProperties='', extensionVersion='1.8.9.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='bca417a8-cb3c-43e0-adf2-6a5fccd7c4c1'.
[2023-03-25T20:10:18.882Z] Incoming HTTP request ends with server failure: correlationId='bca417a8-cb3c-43e0-adf2-6a5fccd7c4c1', authorizationSource='Management', authorizationAction='', operationName='/UNKNOWNOPERATION', httpMethod='POST', hostName='localhost', targetUri='http://localhost:8000/runtime/webhooks/workflow/api/management/generateXslt?api-version=2019-10-01-edge-preview', userAgent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.76.2 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36', clientRequestId='', clientSessionId='', clientIpAddress='', clientApplicationId='', apiVersion='2019-10-01-edge-preview', contentLength='-1', serviceRequestId=':bca417a8-cb3c-43e0-adf2-6a5fccd7c4c1', durationInMilliseconds='168', httpStatusCode='500', exceptionMessage='', errorCode='', failureCause='Service', errorMessage='', referer='<null>', commandName='', parameterSetName='', contentType='application/json; charset=utf-8', contentEncoding='', armServiceRequestId='', organizationId='', activityVector='IN', locale='en-US', additionalProperties='', targetResourceProvider='', targetResourceType='', extensionVersion='1.8.9.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='bca417a8-cb3c-43e0-adf2-6a5fccd7c4c1'.

### Expected behavior

Map should be saved successfully. If not, should provide meaningful error message.

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by shailesh-agre** [comment]
This issue is because backend service and UI are out of sync.
Used previous stable version v0.2.109 and it started working.
I will test with new version once both are in sync.
