### ISSUE TITLE
VSCode Workflow Designer Does not open after Upgrade to 2.0.16 version

### ISSUE THREAD

**Issue by axp972** [Azure/LogicAppsUX#1903]
### Describe the Bug with repro steps

**OS Specificication**
Windows 10 - 64bit
Logic App Extension Version- 2.0.16
VS Code Version- 
![image](https://user-images.githubusercontent.com/75454539/229587864-4926b5ca-93d3-4536-87b6-2ccacd76ca2a.png)

**Symptoms**
Workflow designer in visual studio code opens a blank window upon trying to open designer by right clicking on workflow file and selecting "Open in Designer".
This is noticed only after upgrade to logic app extension version- 2.0.16, it works fine again upon rolling back to version- 1.0.49.

### Workflow JSON

```json
This happens with any logic app workflow.
```

### Screenshots or Videos

https://user-images.githubusercontent.com/75454539/229597737-03479512-e43d-4674-bfdf-9b3af1a56e7b.mp4

### Browser

Visual Studio Code

**Comment by ccastrotrejo** [comment]
Hi @axp972 thanks for raising the issue. 
1.- When you first opened the designer, did you selected any resources group, or did you click on the `skip for now` option? This can also be checked by looking at your local.settings.json and see if `WORKFLOWS_SUBSCRIPTION_ID` has any value. 

2.- Is there any error in the terminal? You can check this by pressing the `Ctrl` + `Shift` +`P` key combination and type  `Toggle Developer Tools`

**Comment by axp972** [comment]
Hi @ccastrotrejo, thanks for looking into it.
1. Yes, I clicked on skip for now. There is no value for WORKFLOWS_SUBSCRIPTION_ID.
2. There are following 3 errors in terminal-

---

[Extension Host] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at OpenDesignerForLocalProject.<anonymous> (c:\Users\axp972\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-2.0.16\main.js:471903:42)
	at Generator.next (<anonymous>)
	at c:\Users\axp972\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-2.0.16\main.js:489213:71
	at new Promise (<anonymous>)
	at Module.__awaiter (c:\Users\axp972\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-2.0.16\main.js:489209:12)
	at OpenDesignerForLocalProject.getWebviewContent (c:\Users\axp972\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-2.0.16\main.js:471886:24)
	at OpenDesignerForLocalProject.<anonymous> (c:\Users\axp972\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-2.0.16\main.js:472184:50)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\axp972\.vscode\extensions\ms-azuretools.vscode-azurelogicapps-2.0.16\main.js:489210:58)

---

main.9c1b70bc975159e5.js:2 Common.ArgumentException: subscriptionId required
    at new $Z (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:1895639)
    at qge (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:2840058)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:2843931
    at Object.$a [as useMemo] (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5450751)
    at t.useMemo (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5565742)
    at ebe (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:2843925)
    at Na (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5446370)
    at Ms (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5458001)
    at Cc (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5504219)
    at vl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5492334)
    at bl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5492262)
    at gl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5492125)
    at ol (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5488932)
    at cl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5489321)
    at _r (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5430211)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5486869

---

main.9c1b70bc975159e5.js:2 Uncaught Common.ArgumentException: subscriptionId required
    at new $Z (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:1895639)
    at qge (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:2840058)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:2843931
    at Object.$a [as useMemo] (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5450751)
    at t.useMemo (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5565742)
    at ebe (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:2843925)
    at Na (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5446370)
    at Ms (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5458001)
    at Cc (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5504219)
    at vl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5492334)
    at bl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5492262)
    at gl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5492125)
    at ol (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5488932)
    at cl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5489321)
    at _r (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5430211)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/axp972/.vscode/extensions/ms-azuretools.vscode-azurelogicapps-2.0.16/webview/main.9c1b70bc975159e5.js:2:5486869

---

Note: I created new project and tried without selecting `skip for now` and selecting a subscription & resource group; then it worked.

**Comment by ccastrotrejo** [comment]
Good to hear that it worked with a resource group. Sorry about it, that is a known issue on our side and will be solved in the next version.

**Comment by axp972** [comment]
Thanks @ccastrotrejo for quick response and fix!
