### ISSUE TITLE
VSCODE_Parameterization_Nuget Based Project_Showing error message while running the flow.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#1956]
### Describe the Bug with repro steps

1. Use an existing local logic app with a workflow that has multiple different connections. ManagedApi, Function, and ServiceProviderOperations sections in connections.json should all have at least 1 connection.

 

2. Make sure that the workflow runs successfully before making any changes. Test this out by getting 1 successful run.

 

3. Create a new file in the root of the project (same level as connections.json) named "parameters.json" as an empty object ("{}").

 

4. Parameterize workflow

4.1. Parameterize some action inputs. For example, if you have a SQL action, you can parameterize the SQL query by using "@parameters('SqlQueryParam')" in the input. For this input you would have to create a matching entry in "parameters.json" that would look like this:

 

"SqlQueryParam": {

"type": "string",

"value": "SELECT * FROM …."

}

 

Note that you can try this with other parameter types as well like: Array, Bool, Float, Int, Object, String.

 

5.  Parameterize connections.json

5.1. Parameterize some values in connections.json. You can parameterize things like "connectionRuntimeUrl" as a string, or "authentication" as an object. Please try multiple different things here and make sure to follow the previous step to add a matching parameter value in parameters.json

6.The flow should be run successfully as expected.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/92098490/230912619-5d72328c-b678-4275-b9f9-a0cc99083984.png)

### Browser

VS Code

### Additional context

Expected:The flow should be run successfully without any error.

Actual:Showing error message related to workflow while running the flow.

Workflow Error: operationName='WorkflowDefinitionProvider.GetFunctionMetadataAsync', message='Workflow processing failed, the response exception is 'Parsing 'functionConnections' value in connections.json file failed. Details: The workflow parameter 'functionAuth' is not found..'', exception='Microsoft.Azure.Workflows.Common.ErrorResponses.ErrorResponseMessageException: Parsing 'functionConnections' value in connections.json file failed. Details: The workflow parameter 'functionAuth' is not found..
[2021-06-04T15:39:33.849Z]    at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.GetResolvedFunctionConnections(InsensitiveDictionary`1 functionConnections, InsensitiveDictionary`1 parameters)
[2021-06-04T15:39:33.852Z]    at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.LoadEdgeConnectionDetails(InsensitiveDictionary`1 parameters)
[2021-06-04T15:39:33.854Z]    at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.ProcessWorkflowFiles()
[2021-06-04T15:39:33.857Z]    at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.GetFunctionMetadataAsync()', extensionVersion='1.0.0.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='00000000-0000-0000-0000-000000000000'.
[2021-06-04T15:39:34.040Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

**Comment by v-prakumar** [comment]
This is known issue in the old designer of VS Code NuGet based.

**Comment by ccastrotrejo** [comment]
[Azure DevOps](https://msazure.visualstudio.com/One/_workitems/edit/10079145/) link

**Comment by v-prakumar** [comment]
@ccastrotrejo Repro in VSIX 2.24.3.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/5644ff95-9dd9-48c7-b5a5-21689e63e350)
