### ISSUE TITLE
Code Designer silently fails to save "incorrect" JSON (with comment)

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2363]
### Describe the Bug with repro steps

1. Create an empty workflow
2. Edit its source code using the Code Designer
3. Comment a block with `//`
4. Attempt to save
5. Observe nothing happens
6. Observer in console the following error:

```
t (in promise) SyntaxError: Unexpected token '/', ..."          //{
      "... is not valid JSON
    at JSON.parse (<anonymous>)
    at a.<anonymous> (DUpsro35kPp9.js:1:4419)
    at UrVujb0xcPvp.js:17:2806
    at Object.next (UrVujb0xcPvp.js:17:2911)
    at a (UrVujb0xcPvp.js:17:1639)
(anonymous) @ DUpsro35kPp9.js:1
```

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "kind": "Stateful",
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "When_messages_are_available_in_a_queue": {
        "type": "ServiceProvider",
        "inputs": {
          "parameters": {
            "queueName": "tenant-request"
          },
          "serviceProviderConfiguration": {
            "connectionName": "azurequeues",
            "operationId": "receiveQueueMessages",
            "serviceProviderId": "/serviceProviders/azurequeues"
          }
        },
        "conditions": [
          //{
          //  "expression": "@equals(triggerBody().resourceType, 'tenant')"
          //}
        ]
      }
    },
    "actions": {
      "Parse_Request": {
        "type": "ParseJson",
        "inputs": {
          "content": "@triggerBody().messageText"
        },
        "runAfter": {}
      }
    },
    "outputs": {}
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/351644/1ecba583-4a83-4ec5-a761-7b556cb69b7d)

### Browser

Edge version 113.0.1774.35

**Comment by Eric-B-Wu** [comment]
we shouldn't be supporting invalid JSONs in our workflow, and comments are not permitted in JSON objects

**Comment by abatishchev** [comment]
I think the designer should provide visible, readable error that the JSON is invalid and can't be saved
