### ISSUE TITLE
Workflow URL is showing up if the request trigger uses relative path parameters

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#2439]
### Describe the Bug with repro steps

1. Create a workflow with relative path parameters
2. Save the workflow and you will see no value in Workflow URL.

Console log:
name: TypeError
stack: **TypeError: this._relativePathParamsValue(...)[this._relativePathParams(...)[(t / 2)]] is not a function**
    at n._setUrlWithPathsandQueries (https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/W-JPfUEKPlhA.js:1:8809)
    at onClick (https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/W-JPfUEKPlhA.js:1:9826)
    at t.invokeClickHandler (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:82:12171)
    at e.invoke (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:95218)
    at Array.<anonymous> (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:102820)
    at e.handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:4915)
    at e.handleEventMessage (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:103122)
    at Array.<anonymous> (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:105310)
    at e.handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:4915)
    at _handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:11722)
    at D (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:11423)
    at e._handler (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:11883)
    at e._processInnerList (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:3606)
    at e._processOuterList (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:3858)
    at e.addItem (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:4041)
    at MessagePort._handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:5807)
From RPC: fx -> Microsoft_Azure_EMA

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/49498706/7c19c25d-5bd9-495c-8f15-01d98f016739)

### Browser

Chrome

**Comment by preetriti1** [comment]
The fix for this is in our current release train ,so closing this issue here as by mid of next week it should make it to production.

**Comment by preetriti1** [comment]
@mohit-jagtiani - What is 2.19.0? Are you not using Portal because this issue is fixed in the Portal for standard workflows and we can also successfully invoke using RunWithPayload using your relative path.

**Comment by mohit-jagtiani** [comment]
@preetriti1 that is your latest designer release at the time I raised this issue
https://github.com/Azure/LogicAppsUX/releases

direct workflow url generated doesnt work still, nor does run with payload option

https://la-esb-devtst-documentsapi-001.ase-esb-devtst-application-001.appserviceenvironment.net/api/get-doucument-file-from-efs/triggers/Get_document_file_request/invoke/documents/%7BdocumentId%7D/%7Brevision%7D/file?api-version=2022-05-01&sp=**%252Ftriggers%252**FGet_document_file_request%252Frun&sv=1.0
