### ISSUE TITLE
"Run with payload" does not work if the request trigger uses relative path parameters

### ISSUE THREAD

**Issue by xuehongg** [Azure/LogicAppsUX#2440]
### Describe the Bug with repro steps

1. Create a workflow with a request trigger with relative path parameters
2. Open "Run with payload" and fill in data. Then click on "Run". It has no response.

Console log:
(anonymous) @ 15cdb65d-4823-4149-a6a1-fd20ae0937f0:1
Dv1seNw9hbMj.js:64 **Uncaught TypeError: this._relativePathParamsValue(...)[this._relativePathParams(...)[(t / 2)]] is not a function**
    at n._setUrlWithPathsandQueries ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/W-JPfUEKPlhA.js:1:8809](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fafd-v2.hosting-ms.portal.azure.net%2Fema%2FContent%2FDynamic%2FW-JPfUEKPlhA.js%3A1%3A8809&data=05%7C01%7Cxuehongg%40microsoft.com%7Cd1a774d5bb74490c3f6008db57e44bb2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638200410272064248%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=On7AJfkZJua7J5Vh2yKxFtFPpzg%2B7hgGFz5xBgE01N8%3D&reserved=0))
    at onClick ([https://afd-v2.hosting-ms.portal.azure.net/ema/Content/Dynamic/W-JPfUEKPlhA.js:1:9826](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fafd-v2.hosting-ms.portal.azure.net%2Fema%2FContent%2FDynamic%2FW-JPfUEKPlhA.js%3A1%3A9826&data=05%7C01%7Cxuehongg%40microsoft.com%7Cd1a774d5bb74490c3f6008db57e44bb2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638200410272064248%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g0YTo4TkpUWGXY%2Bj%2BSHKKXuMq%2Bm3TP26cKXM%2Bwq%2BqXI%3D&reserved=0))
    at t.invokeClickHandler (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:82:12171)
    at e.invoke (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:95218)
    at Array.<anonymous> (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:102820)
    at e.handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:4915)
    at e.handleEventMessage (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:103122)
    at Array.<anonymous> (https://ms.portal.azure.com/Content/Dynamic/fi7NwFeX8cz_.js:1:105310)
    at e.handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:4915)
    at _handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:11722)
    at D (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:11423)
    at e._handler (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:11883)
    at e._processInnerList (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:3606)
    at e._processOuterList (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:3858)
    at e.addItem (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:4041)
    at MessagePort._handleMessage (https://ms.portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:64:5807)
From RPC: fx -> Microsoft_Azure_EMA

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/49498706/d175c2f8-0b90-4e04-a427-308e69f9079d)

### Browser

Chrome

**Comment by preetriti1** [comment]
The fix for this is in our current release train ,so closing this issue here as by mid of next week it should make it to production.
