### ISSUE TITLE
Intermittently unable to expand expression editor

### ISSUE THREAD

**Issue by BrianCollet** [Azure/LogicAppsUX#2788]
### Describe the Bug with repro steps

1. Go to workflow designer
2. Select set variable action (not sure if occurs with other actions, but happened with this action in my experience)
3. Click in the value input box
4. Select insert expression
5. The expression editor opens (although not fully) and trying to expand it does not work and also unable to type anything into it
6. Console log errors pasted below

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/50160870/96d2b0e6-0cf2-4f96-b26d-c0009cdf268e)

### Browser

Edge, Chrome

### Additional context

Edge console logs:
6a57e33c-111c-4f67-b621-ecfb3314c387:1 Extension: HubsExtension
XF04yqkBGY3O.js:341 Version: 11.210.6.1 (v11.210.0.1#88c2b04310.230614-0057) Signed
Session: 0b699dcc7b4f4c4ab53f35430c5b155b
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
 Extension: Microsoft_Azure_PIMCommon
6a57e33c-111c-4f67-b621-ecfb3314c387:1 Extension: WebsitesExtension
2A7lcmKw7zxp.js:28 2023-06-19T12:50:28.363Z [info][WorkflowAppOverviewBlade][tabs][notification-count] - Logged '0' notifications
2A7lcmKw7zxp.js:28 2023-06-19T12:52:21.173Z [info][WorkflowAppOverviewBlade][tabs][notification-count] - Logged '0' notifications
6a57e33c-111c-4f67-b621-ecfb3314c387:1 Extension: Microsoft_Azure_EMA
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Permissions-Policy header: Unrecognized feature: 'battery'.
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Permissions-Policy header: Unrecognized feature: 'battery'.
SV6nrji5Rf7O.js:3  Object
onError @ SV6nrji5Rf7O.js:3
graph.windows.net/myorganization/policies?api-version=1.6:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
graph.windows.net/myorganization/policies?api-version=1.6:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
SV6nrji5Rf7O.js:3  Object
onError @ SV6nrji5Rf7O.js:3
SV6nrji5Rf7O.js:3  Object
onError @ SV6nrji5Rf7O.js:3
editor.main.js:1 
        
        
        Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR
editor.main.js:1 
        
        
        Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR
editor.main.js:1 
        
        
        Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR
V2wCymnt091J.js:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
graph.windows.net/myorganization/policies?api-version=1.6:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
graph.windows.net/myorganization/policies?api-version=1.6:1 
        
        
        Failed to load resource: the server responded with a status of 400 (Bad Request)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
sandbox-55-7.reactbl…b155b#postParams/:1  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)
SV6nrji5Rf7O.js:3  Uncaught (in promise) Error: Manual require of the following modules failed; ["vs/editor/editor.main" : {Error: define for "vs/editor/editor.main" wasn't called because of a script error for "[https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/editor/editor.main.js?retryAttempt=1.297172645240478]", trying Ajax call.}];
    at mn (V2wCymnt091J.js:1:3458)
    at u (V2wCymnt091J.js:1:10499)

Chrome console logs:
XF04yqkBGY3O.js:341 Version: 11.210.6.1 (v11.210.0.1#88c2b04310.230614-0057) Signed
Session: 00516c0ea3554c3c98667f2f0f767dc8
XF04yqkBGY3O.js:64 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
(anonymous) @ XF04yqkBGY3O.js:64
94970d34-bcdf-4939-8ee1-dffbea0706e7:1 Extension: HubsExtension
94970d34-bcdf-4939-8ee1-dffbea0706e7:1 Extension: WebsitesExtension
94970d34-bcdf-4939-8ee1-dffbea0706e7:1 Extension: Microsoft_Azure_EMA
2A7lcmKw7zxp.js:28 2023-06-19T17:06:19.689Z [info][WorkflowAppOverviewBlade][tabs][notification-count] - Logged '0' notifications
XF04yqkBGY3O.js:64 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
(anonymous) @ XF04yqkBGY3O.js:64
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Permissions-Policy header: Unrecognized feature: 'battery'.
XF04yqkBGY3O.js:64 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
(anonymous) @ XF04yqkBGY3O.js:64
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Permissions-Policy header: Unrecognized feature: 'battery'.
SV6nrji5Rf7O.js:3 Object
onError @ SV6nrji5Rf7O.js:3
sandbox-51-3.reactblade.portal.azure.net/React/vs/base/worker/workerMain.js#editorWorkerService:1     Failed to load resource: the server responded with a status of 404 ()
simpleWorker.ts:36 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
g @ simpleWorker.ts:36
simpleWorker.ts:38 undefined
g @ simpleWorker.ts:38
simpleWorker.ts:38 undefined
g @ simpleWorker.ts:38
DevTools failed to load source map: Could not load content for https://portal.azure.com/Content/11.210.6.111.210.0.188204310.230614-0057/Scripts/@microsoft/ms.analytics-web.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://afd.hosting.portal.azure.net/ema/Content/Dynamic/DataFetchers\DesignerEditor.DataFetcher.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://afd.hosting.portal.azure.net/ema/Content/Dynamic/Views\DesignerEditor.ReactView.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Eric-B-Wu** [comment]
@BrainCollet can you try going to edge://flags/#enable-quic and disabling that experiment? I believe this is happening because monaco/react (what the expression editor is built off of) uses a CDN to get its data. I'll look into seeing if I can load monaco from node modules instead of cdn
