### ISSUE TITLE
VS Code_Azure Blob: Getting error message in logs even after workflow is debugged successfully.

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3470]
### Describe the Bug with repro steps 

1\.Create a stateful or stateless workflow in VS code.

 2\.Add request trigger, Checks whether blob exists, delete blob, read blob content actions.

 3\.Add the Blob names, details and save the workflow.

 4\.Debugging should be successful without any error logs.

**Expected:** Debugging should be successful without any error logs.

**Actual:**Debugging is successful but with lot of error logs.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Check_whether_blob_exists": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "containerName": "xyz",
                        "blobName": "mani.txt"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "AzureBlob",
                        "operationId": "blobExists",
                        "serviceProviderId": "/serviceProviders/AzureBlob"
                    }
                },
                "runAfter": {}
            },
            "Delete_blob": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "containerName": "xyz",
                        "blobName": "uploaded @ 2709"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "AzureBlob",
                        "operationId": "deleteBlob",
                        "serviceProviderId": "/serviceProviders/AzureBlob"
                    }
                },
                "runAfter": {
                    "Check_whether_blob_exists": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Read_blob_content": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "containerName": "xyz",
                        "blobName": "InputJson.txt"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "AzureBlob",
                        "operationId": "readBlob",
                        "serviceProviderId": "/serviceProviders/AzureBlob"
                    }
                },
                "runAfter": {
                    "Delete_blob": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Upload_blob_to_storage_container": {
                "type": "ServiceProvider",
                "inputs": {
                    "parameters": {
                        "containerName": "xyz",
                        "blobName": "uploading blob@1018",
                        "content": "uploaded successfully"
                    },
                    "serviceProviderConfiguration": {
                        "connectionName": "AzureBlob",
                        "operationId": "uploadBlob",
                        "serviceProviderId": "/serviceProviders/AzureBlob"
                    }
                },
                "runAfter": {
                    "Read_blob_content": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](<https://github.com/Azure/LogicAppsUX/assets/113517384/9b74f9b9-b470-40bf-9a04-417f3a837df4>)

**Error logs details:**

Error message: correlationId='05f9b96d-5261-45e5-b143-a69335f9b690', operationName='AzureBlob.AzureBlobServiceOperationProvider.HandleStorageException', message='The specified resource name length is not within the permissible limits.

 RequestId:882aab19-101e-001e-4abf-0165f4000000

 Time:2023-10-18T12:34:42.1822422Z

 [2023-10-18T12:34:41.956Z] Status: 400 (The specified resource name length is not within the permissible limits.)

 [2023-10-18T12:34:41.957Z] ErrorCode: OutOfRangeInput

 [2023-10-18T12:34:41.958Z]

 [2023-10-18T12:34:41.958Z] Content:

 [2023-10-18T12:34:41.959Z] `OutOfRangeInput`The specified resource name length is not within the permissible limits. RequestId:882aab19-101e-001e-4abf-0165f4000000 Time:2023-10-18T12:34:42.1822422Z

 [2023-10-18T12:34:41.959Z]

 [2023-10-18T12:34:41.960Z] Headers:

 [2023-10-18T12:34:41.961Z] Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

 [2023-10-18T12:34:41.962Z] x-ms-request-id: 882aab19-101e-001e-4abf-0165f4000000

 [2023-10-18T12:34:41.962Z] x-ms-client-request-id: 2e4e40e5-1fce-4401-ac9b-a12039f66b0e

 [2023-10-18T12:34:41.963Z] x-ms-version: 2021-08-06

 [2023-10-18T12:34:41.964Z] x-ms-error-code: OutOfRangeInput

 [2023-10-18T12:34:41.965Z] Date: Wed, 18 Oct 2023 12:34:41 GMT

 [2023-10-18T12:34:41.966Z] Content-Length: 256

 [2023-10-18T12:34:41.967Z] Content-Type: application/xml

 [2023-10-18T12:34:41.968Z] ', exception='Azure.RequestFailedException: The specified resource name length is not within the permissible limits.

 RequestId:882aab19-101e-001e-4abf-0165f4000000

 Time:2023-10-18T12:34:42.1822422Z

 [2023-10-18T12:34:41.968Z] Status: 400 (The specified resource name length is not within the permissible limits.)

 [2023-10-18T12:34:41.969Z] ErrorCode: OutOfRangeInput

 [2023-10-18T12:34:41.970Z]

 [2023-10-18T12:34:41.970Z] Content:

 [2023-10-18T12:34:41.971Z] `OutOfRangeInput`The specified resource name length is not within the permissible limits. RequestId:882aab19-101e-001e-4abf-0165f4000000 Time:2023-10-18T12:34:42.1822422Z

 [2023-10-18T12:34:41.972Z]

 [2023-10-18T12:34:41.972Z] Headers:

 [2023-10-18T12:34:41.973Z] Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

 [2023-10-18T12:34:41.974Z] x-ms-request-id: 882aab19-101e-001e-4abf-0165f4000000

 [2023-10-18T12:34:41.974Z] x-ms-client-request-id: 2e4e40e5-1fce-4401-ac9b-a12039f66b0e

 [2023-10-18T12:34:41.975Z] x-ms-version: 2021-08-06

 [2023-10-18T12:34:41.976Z] x-ms-error-code: OutOfRangeInput

 [2023-10-18T12:34:41.976Z] Date: Wed, 18 Oct 2023 12:34:41 GMT

 [2023-10-18T12:34:41.977Z] Content-Length: 256

 [2023-10-18T12:34:41.979Z] Content-Type: application/xml

 [2023-10-18T12:34:41.979Z] 

 [2023-10-18T12:34:41.981Z] at Azure.Storage.Blobs.ContainerRestClient.GetPropertiesAsync(Nullable`1 timeout, String leaseId, CancellationToken cancellationToken) [2023-10-18T12:34:41.982Z] at Azure.Storage.Blobs.BlobContainerClient.GetPropertiesInternal(BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken) [2023-10-18T12:34:41.983Z] at Azure.Storage.Blobs.BlobContainerClient.ExistsInternal(Boolean async, CancellationToken cancellationToken) [2023-10-18T12:34:41.984Z] at Azure.Storage.Blobs.BlobContainerClient.ExistsAsync(CancellationToken cancellationToken) [2023-10-18T12:34:41.984Z] at Microsoft.Azure.Workflows.ServiceProviders.AzureBlob.Providers.AzureBlobServiceOperationProvider.UploadblobContentAsync(BlobServiceClient blobServiceClient, BlobPathInformation blobPathInformation, JToken blobContent, Boolean overrideIfExists)', organizationId='', activityVector='IN.05', additionalProperties='{"ParentActivityId":"00-6cb6077e5a42b1db0dae21bdf2d5e679-e1e9196d111d9900-00"}', extensionVersion='1.44.1.0', siteName='UNDEFINED_SITE_NAME', slotName='', activityId='715d1908-d601-4c6a-b0a9-dd304e352167'. [2023-10-18T12:34:41.994Z] Error message: correlationId='05f9b96d-5261-45e5-b143-a69335f9b690', operationName='ServiceProviderActionJob.ExecuteServiceProviderOperationAndHandleException', message='Service Provider: '/serviceProviders/AzureBlob' Operation Id: 'uploadBlob' resulted in: The specified resource name length is not within the permissible limits. RequestId:882aab19-101e-001e-4abf-0165f4000000 Time:2023-10-18T12:34:42.1822422Z [2023-10-18T12:34:41.996Z] Status: 400 (The specified resource name length is not within the permissible limits.) [2023-10-18T12:34:41.997Z] ErrorCode: OutOfRangeInput [2023-10-18T12:34:41.998Z] [2023-10-18T12:34:41.998Z] Content: [2023-10-18T12:34:41.999Z] &lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;Error&gt;<code>OutOfRangeInput</code>&lt;Message&gt;The specified resource name length is not within the permissible limits. RequestId:882aab19-101e-001e-4abf-0165f4000000 Time:2023-10-18T12:34:42.1822422Z&lt;/Message&gt;&lt;/Error&gt; [2023-10-18T12:34:42.000Z] [2023-10-18T12:34:42.001Z] Headers: [2023-10-18T12:34:42.002Z] Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0 [2023-10-18T12:34:42.003Z] x-ms-request-id: 882aab19-101e-001e-4abf-0165f4000000 [2023-10-18T12:34:42.004Z] x-ms-client-request-id: 2e4e40e5-1fce-4401-ac9b-a12039f66b0e [2023-10-18T12:34:42.005Z] x-ms-version: 2021-08-06 [2023-10-18T12:34:42.005Z] x-ms-error-code: OutOfRangeInput [2023-10-18T12:34:42.006Z] Date: Wed, 18 Oct 2023 12:34:41 GMT [2023-10-18T12:34:42.007Z] Content-Length: 256 [2023-10-18T12:34:42.007Z] Content-Type: application/xml [2023-10-18T12:34:42.008Z] ', exception='Azure.RequestFailedException: The specified resource name length is not within the permissible limits. RequestId:882aab19-101e-001e-4abf-0165f4000000 Time:2023-10-18T12:34:42.1822422Z [2023-10-18T12:34:42.008Z] Status: 400 (The specified resource name length is not within the permissible limits.) [2023-10-18T12:34:42.009Z] ErrorCode: OutOfRangeInput [2023-10-18T12:34:42.010Z] [2023-10-18T12:34:42.011Z] Content: [2023-10-18T12:34:42.012Z] &lt;?xml version="1.0" encoding="utf-8"?&gt;&lt;Error&gt;<code>OutOfRangeInput</code>&lt;Message&gt;The specified resource name length is not within the permissible limits. RequestId:882aab19-101e-001e-4abf-0165f4000000 Time:2023-10-18T12:34:42.1822422Z&lt;/Message&gt;&lt;/Error&gt; [2023-10-18T12:34:42.013Z] [2023-10-18T12:34:42.014Z] Headers: [2023-10-18T12:34:42.014Z] Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0 [2023-10-18T12:34:42.015Z] x-ms-request-id: 882aab19-101e-001e-4abf-0165f4000000 [2023-10-18T12:34:42.016Z] x-ms-client-request-id: 2e4e40e5-1fce-4401-ac9b-a12039f66b0e [2023-10-18T12:34:42.017Z] x-ms-version: 2021-08-06 [2023-10-18T12:34:42.018Z] x-ms-error-code: OutOfRangeInput [2023-10-18T12:34:42.019Z] Date: Wed, 18 Oct 2023 12:34:41 GMT [2023-10-18T12:34:42.020Z] Content-Length: 256 [2023-10-18T12:34:42.020Z] Content-Type: application/xml [2023-10-18T12:34:42.021Z] [2023-10-18T12:34:42.021Z] at Azure.Storage.Blobs.ContainerRestClient.GetPropertiesAsync(Nullable`1 timeout, String leaseId, CancellationToken cancellationToken)

 [2023-10-18T12:34:42.022Z] at Azure.Storage.Blobs.BlobContainerClient.GetPropertiesInternal(BlobRequestConditions conditions, Boolean async[2023-10-18T12:34:42.023Z] at Azure.Storage.Blobs.BlobContainerClient.ExistsAsync(CancellationToken cancellationToken)

 [2023-10-18T12:34:42.024Z] at Microsoft.Azure.Workflows.ServiceProviders.AzureBlob.Providers.AzureBlobServiceOperationProvider.UploadblobContentAsync(BlobServiceClient blobServiceClient, BlobPathInformation blobPathInformation, JToken blobContent, Boolean overrideIfExists)', organizationId='', activityVector='IN.05', additionalProperties='{"ParentActivityId":"00-6cb6077e5a42b1db0dae21bdf2d5e679-e1e9196d111d9900-00"}', extensionVersion='1.44.1.0', siteName='UNDEFINED\_SITE\_NAME', slotName='', activityId='715d1908-d601-4c6a-b0a9-dd304e352167'.

 [2023-10-18T12:34:42.213Z] Executed 'Functions.WorkflowDispatcher' (Succeeded, Id=ed65d5a1-2e75-47ca-a424-d768a2ef8418, Duration=1533ms)

### Browser

**1\.VS Code extension** \- ​​vsix icon[ vscode-azurelogicapps-2.72.1.vsix](<https://microsoft.sharepoint.com/:u:/t/LogicApps/EfKWqLA0W0ZEvopnY8wo_tkBY9WSkRtgWk-niBfAd47iPw?e=ohFYeL&xsdata=MDV8MDF8di1pdHJhbXlhQG1pY3Jvc29mdC5jb218MWY4ZWNjOWQwMTMwNGI2N2E0ZGYwOGRiY2YzN2ZhZGF8NzJmOTg4YmY4NmYxNDFhZjkxYWIyZDdjZDAxMWRiNDd8MXwwfDYzODMzMTYxMTgxMjIxOTAyMnxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MzAwMHx8fA%3d%3d&sdata=VUxqbU9kQ1VKV2ZmbFgvbFhnMExMUHVnQlE4TE1mVHRmYjdmOXhGNG5tVT0%3d>)

**2\.NuGet package:** [https://artprodeussu2.artifacts.visualstudio.com/A41bf5486-7392-4b7a-a7e3-a735c767e3b3/b32aa71e-8ed2-41b2-9d77-5bc261222004/\_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1/content?format=file&subPath=%2fMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg](<https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fartprodeussu2.artifacts.visualstudio.com%2fA41bf5486-7392-4b7a-a7e3-a735c767e3b3%2fb32aa71e-8ed2-41b2-9d77-5bc261222004%2f_apis%2fartifact%2fcGlwZWxpbmVhcnRpZmFjdDovL21zYXp1cmUvcHJvamVjdElkL2IzMmFhNzFlLThlZDItNDFiMi05ZDc3LTViYzI2MTIyMjAwNC9idWlsZElkLzgxMTY0NTE3L2FydGlmYWN0TmFtZS9kcm9wX2J1aWxkX0J1aWxkQXJ0aWZhY3RzX1dpbmRvd3M1%2fcontent?format%3Dfile%26subPath%3D%252FMicrosoft.Azure.Workflows.WebJobs.Extension.1.44.1.nupkg&data=05%7c01%7cv-itramya%40microsoft.com%7cae053676d4a4467f085308dbcee1c051%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638331241613333478%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=whaLLdJIMjsic5AHmCk6Xb4GDEnNzQdbhbmd7AYE66o%3D&reserved=0>)

**3\.Extension Bundle (CDN URL):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting](<https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fcdnforlogicappsv2.blob.core.windows.net%2flogicapps-vendortesting&data=05%7c01%7cv-itramya%40microsoft.com%7cae053676d4a4467f085308dbcee1c051%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638331241613343570%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=p0LTFBnMqK0OtC0tKtfn3DUiGfH9UT6wd0kzurKV1po%3D&reserved=0>)

**4\.Extension Bundle (Direct Download):** [https://cdnforlogicappsv2.blob.core.windows.net/logicapps-vendortesting/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.44.1/Microsoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1\_any-any.zip](<https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fcdnforlogicappsv2.blob.core.windows.net%2flogicapps-vendortesting%2fExtensionBundles%2fMicrosoft.Azure.Functions.ExtensionBundle.Workflows%2f1.44.1%2fMicrosoft.Azure.Functions.ExtensionBundle.Workflows.1.44.1_any-any.zip&data=05%7c01%7cv-itramya%40microsoft.com%7cae053676d4a4467f085308dbcee1c051%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638331241613350230%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=Xir1h2Cqma1OrxIQHPS7EZ5mrVoth9%2BjUtVWPAH1auQ%3D&reserved=0>)

### Additional context

*No response*

AB#25522446

**Comment by vgouth** [comment]
Issue is seen only in nuget artifact

**Comment by ccastrotrejo** [comment]
Not repro anymore. If this issue occurs again, I will take a further look
