### ISSUE TITLE
version 4.94 monitor view throw exception on value.reduce is not a function

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#5706]
### Describe the Bug with repro steps 

I am trying to adopt latest version 4.94. I noticed a weird error. In monitor view, if I open operation panel, click it, then switch to a different action to open operation panel. it throws exception value.reduce is not a function. It sounds like a regression as I didn't see this behavior in previous version 4.51.5 we used

copypaste.ts:56 Uncaught (in promise) TypeError: value.reduce is not a function

 at onRunRepetitionsSuccess (copypaste.ts:56:37)

 at notifyManager.mjs:49:1

 at notifyFn (notifyManager.mjs:8:1)

 at notifyManager.mjs:62:1

 at Array.forEach ()

 at notifyManager.mjs:61:1

 at batchNotifyFn (notifyManager.mjs:12:1)

 at notifyManager.mjs:60:1

![image](<https://github.com/user-attachments/assets/d9f710f8-d152-40e2-9e77-204558c1b042>)

![monitorViewClickBoard](<https://github.com/user-attachments/assets/18a4a7a7-799e-46e3-92d4-7b9551065d1e>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by Xiaoyu-Huang** [comment]
issue on host side, the scopepetition call returns a wrong schema
