### ISSUE TITLE
Custom Code WeatherForecast sample does not work for Net 47 and Net 8

### ISSUE THREAD

**Issue by StephenWThomas** [Azure/LogicAppsUX#6082]
### Describe the Bug with repro steps 

1. Build a new environment using VS Code in a new VM. (also tested with an existing environment with updated Functions and C# from 2024-11-12) 
2. Install Azure Account and Logic App Standard extensions 
3. Create a new workspace following this: [https://learn.microsoft.com/en-us/azure/logic-apps/create-run-custom-code-functions](<https://learn.microsoft.com/en-us/azure/logic-apps/create-run-custom-code-functions>) 
4. Either .Net 4.7 or .Net 8 workspaces do not work, giving the error message below when trying to run locally 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Call_a_local_function_in_this_logic_app": {
        "type": "InvokeFunction",
        "inputs": {
          "functionName": "Fun47",
          "parameters": {
            "zipCode": 85396,
            "temperatureScale": "Celsius"
          }
        },
        "runAfter": {}
      },
      "Response": {
        "type": "Response",
        "kind": "http",
        "inputs": {
          "statusCode": 200,
          "body": "@body('Call_a_local_function_in_this_logic_app')"
        },
        "runAfter": {
          "Call_a_local_function_in_this_logic_app": [
            "Succeeded"
          ]
        }
      }
    },
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http",
        "inputs": {}
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {}
  },
  "kind": "Stateful"
}
```

### Screenshots or Videos

Sometimes I see this message:

![Image](<https://github.com/user-attachments/assets/07530a7c-c644-4071-aa01-a13e90f1a412>)

### Browser

VS Code, latest update

### Additional context

Note that today, the Azure Functions extension was updated on 2024-11-12. C# was updated 11-12 as well. I think one of them is causing the issue.

Also, the installation of the Azure Logic App Standard extension now requires .Net 9. Existing installs do not seem to need this but they still have the issue.

Error Message:

 [2024-11-13T03:15:46.080Z] Workflow 'Stateful1' validation and creation failed. Error: 'The 'Call\_a\_local\_function\_in\_this\_logic\_app' action doesn't have function metadata where a function is named 'Fun47'. Make sure that the function.json file, which is located in the 'C:\Demo\CCEight\LogicApp\bin\Debug\net6.0/lib/custom/Fun47' folder, isn't empty. This folder usually has the same name as your function.'

 [2024-11-13T03:15:46.083Z] Workflow Error: operationName='WorkflowFunctionDefinitionProvider.ProcessWorkflow', message='Workflow 'Stateful1' validation and creation failed. Error: 'The 'Call\_a\_local\_function\_in\_this\_logic\_app' action doesn't have function metadata where a function is named 'Fun47'. Make sure that the function.json file, which is located in the 'C:\Demo\CCEight\LogicApp\bin\Debug\net6.0/lib/custom/Fun47' folder, isn't empty. This folder usually has the same name as your function.'', exception='Microsoft.Azure.Workflows.Common.ErrorResponses.ErrorResponseMessageException: The 'Call\_a\_local\_function\_in\_this\_logic\_app' action doesn't have function metadata where a function is named 'Fun47'. Make sure that the function.json file, which is located in the 'C:\Demo\CCEight\LogicApp\bin\Debug\net6.0/lib/custom/Fun47' folder, isn't empty. This folder usually has the same name as your function.

 [2024-11-13T03:15:46.084Z] at Microsoft.Azure.Workflows.Web.Engines.EdgeFlowDefinitionValidationEngine.ValidateFlowRunActionTypeInvokeAction(String actionName, FlowTemplateAction action)

 [2024-11-13T03:15:46.085Z] at Microsoft.Azure.Workflows.Web.Engines.EdgeFlowDefinitionValidationEngine.OnValidateFlowAction(FlowPropertiesDefinition definition, String flowName, String actionName, InsensitiveDictionary`1 parameterValues, FlowOperationConfiguration flowOperationConfiguration, Boolean hasOpenApiOperationInWorkflow, IntegrationAccount integrationAccount) [2024-11-13T03:15:46.086Z] at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowAction(FlowPropertiesDefinition definition, String flowName, String actionName, InsensitiveDictionary`1 parameterValues, Boolean hasOpenApiOperationInWorkflow, Nullable`1 flowKind, IntegrationAccount integrationAccount) [2024-11-13T03:15:46.087Z] at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowActions(FlowPropertiesDefinition definition, InsensitiveDictionary`1 parameterValues, String flowName, IntegrationAccount integrationAccount)

 [2024-11-13T03:15:46.088Z] at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlowTemplate(FlowPropertiesDefinition definition, InsensitiveDictionary`1 templateParameters, String flowName, IntegrationAccount integrationAccount, InsensitiveDictionary`1 appSettings)

 [2024-11-13T03:15:46.089Z] at Microsoft.Azure.Workflows.Data.Engines.FlowDefinitionValidationEngine.ValidateFlow(String flowName, Flow existingFlow, FlowPropertiesDefinition definition, IntegrationAccount integrationAccount, InsensitiveDictionary`1 appSettings) [2024-11-13T03:15:46.090Z] at Microsoft.Azure.Workflows.Web.Engines.EdgeFlowWebManagementEngine.ValidateAndGetFlowIfExists(String subscriptionId, String resourceGroup, String flowName, FlowPropertiesDefinition flowPropertiesDefinition, EdgeConnectionReferencesDefinition edgeConnectionReferencesDefinition) [2024-11-13T03:15:46.091Z] at Microsoft.Azure.Workflows.Web.Engines.EdgeFlowWebManagementEngine.ValidateAndCreateFlow(String appName, String flowName, FlowPropertiesDefinition flowPropertiesDefinition, String resourceGroup) [2024-11-13T03:15:46.092Z] at Microsoft.WindowsAzure.ResourceStack.Common.Algorithms.AsyncRetry.Retry(Func`1 action, Int32 retryCount, TimeSpan retryInterval, CancellationToken cancellationToken, Nullable`1 retryTimeout, Func`2 isRetryable, Action`1 errorAction, Func`2 retryAfter)

 [2024-11-13T03:15:46.093Z] at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.<>c\_\_DisplayClass87\_0.<b\_\_0>d.MoveNext()

 [2024-11-13T03:15:46.094Z] --- End of stack trace from previous location ---

 [2024-11-13T03:15:46.095Z] at Microsoft.Azure.Workflows.Templates.Engines.TemplateEngine.HandleTemplateException[T\]\(Func`1 protectedMethod, HttpStatusCode statusCode) [2024-11-13T03:15:46.096Z] at Microsoft.Azure.Workflows.WebJobs.Extensions.Initialization.WorkflowFunctionDefinitionProvider.ProcessWorkflow(FlowFunction flowFunction, ConcurrentDictionary`2 flowsProcessed)', extensionVersion='1.94.13.0', siteName='UNDEFINED\_SITE\_NAME', slotName='', activityId='8057802d-04d0-4bfe-97cb-44a631e12e5c'.

**Comment by ccastrotrejo** [comment]
Hi @StephenWThomas thanks for raising this issue.
At what stage of creating the workspace does these errors shows?
Did you build and compiled the function side project with the `dotner restore` and `dotnet build` command?

**Comment by StephenWThomas** [comment]
It is at the very end of creating the solution after the workspace with the demo Weather custom code project for .Net 4.7 and .Net 8 is created.  When I try to locally run the Logic App without any breakpoints, select it in Run - Debug.  Crash!

Today, I tried again with a new VM.  It seemed to work as long as I had .Net 9.  I didn't try it with .Net 8.

On my work laptop, I had the same issue with it not working.  Today I installed .Net 9 and remove and re-added the Logic App Standard Extension.
The workspace I created last night never worked and still doesn't.

I created a new one today, and it work just like it did Friday.

I've been giving some live demos so I have ran this many times over the past few days.  Yesterday, it didn't work as it did Friday for a brand new, clean Windows 11 VM with brand new VS Code install.  I do know, that later in the day yesterday when I installed the LA Standard Extension it started prompting me to install .Net 9.  It didn't do that in the morning.

Maybe it was just bad timing and things where inconsistent in the terms of extension downloads for a few hours when I giving another live demo that didn't work.

Stephen W. Thomas

**Comment by StephenWThomas** [comment]
Today, 2024-11-13, a new release of C# and Azue Function extensions was available to replace the ones from yesterday, dated 2024-11-12.

This has resolved the issues I was having, so I assume it was related to the updated older version.
