### ISSUE TITLE
[VSCode] - Error cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by mohamed18123** [Azure/LogicAppsUX#6274]
Does this occur consistently?

Repro steps:

1\.

2\.

Action: autoStartDesignTime

Error type: TypeError

Error Message: Cannot read properties of undefined (reading 'uri')

Version: 4.107.4

OS: win32

OS Release: 10.0.22631

Product: Visual Studio Code

Product Version: 1.96.0

Language: en

<details><summary>Call Stack</summary>¨NBSP;<p>¨NBSP;</p><p> </p></details>

**Comment by ccastrotrejo** [comment]
Hi all thanks for raising this issue.  I have a couple of questions.

- Does this happen everytime you open vscode extension with the Logic Apps Standard extension activated?
- When this error happened, did you have a logic app project opened in vscode?

**Comment by diogocatossi** [comment]
Hey there. I'm experiencing the same issue.  

If VSCode opens empty, single file or a folder there's no error. 
It only happens when opening a workspace.

Error:
Cannot read properties of undefined (reading 'uri')
![Image](https://github.com/user-attachments/assets/f8474a56-0226-42e3-a35f-12bc5ffedbb3)

From ExtHost.log I can see the following trace:
`2025-01-07 13:53:55.284 [error] TypeError: Cannot read properties of undefined (reading 'uri')
    at tryGetLogicAppProjectRoot (c:\Users\catossid\.vscode\extensions\src\app\utils\verifyIsProject.ts:45:84)
    at verifyLocalConnectionKeys (c:\Users\catossid\.vscode\extensions\src\app\utils\appSettings\connectionKeys.ts:16:31)
2025-01-07 13:53:55.336 [error] TypeError: Cannot read properties of undefined (reading 'uri')
    at tryGetLogicAppProjectRoot (c:\Users\catossid\.vscode\extensions\src\app\utils\verifyIsProject.ts:45:84)
    at promptParameterizeConnections (c:\Users\catossid\.vscode\extensions\src\app\commands\parameterizeConnections.ts:30:31)
`

**Comment by ccastrotrejo** [comment]
Hi @diogocatossi thanks for letting us know this issue. We have seen this issue, and there is an ongoing effort on fixing this issue and making this experience more friendly in the following PR https://github.com/Azure/LogicAppsUX/pull/6310

As for now whenever there are multiple Logic App projects there is a wizard like this so you can select the logic app project on it. Were you able to see it and select the proper project folder?
<img width="712" alt="Image" src="https://github.com/user-attachments/assets/96bf67af-8705-48a3-b4ca-ba1d3aee23ce" />

**Comment by diogocatossi** [comment]
@ccastrotrejo, at least for me, there's no relation with open Logic Apps code/projects. Any workspace we open even if doesn't contain any Logic Apps reference the extension itself fails and it doesn't show up at all in the Azure activity bar:

![Image](https://github.com/user-attachments/assets/cfaf2072-ecc7-40a4-bbdd-5044b8059217)

**Comment by ccastrotrejo** [comment]
Hi @diogocatossi since Version 2.15.15 and later: The Azure Logic Apps extension now follows the design pattern that Azure extensions follow. Now, your remote logic apps still appear in the Azure window, but in the Resources section instead. That doesn't necessarily means that is not failing.

**Comment by ppanchal-mobiz** [comment]
I am sorry, what is the conclusion? I am still facing this issue and am waiting for the resolution. I still see the message `Cannot read properties of undefined (reading 'uri')` every time I open a multi-root workspace that does not contain any logicapp project. Thank you.

**Comment by ccastrotrejo** [comment]
Hi @ppanchal-mobiz thats really hard to tell what is going on here. Must of our actions depend on whether exist a logic app project in the workspace or not. Is there any other error you get?

**Comment by ppanchal-mobiz** [comment]
> [@ppanchal-mobiz](https://github.com/ppanchal-mobiz) I see so neither of the folders root, frontend, backend contain a logic app project? For some reason the extension is resolving as the 3 of them contain a logic app project. I will take a look at it

Thank you, @ccastrotrejo, yes none of them contain a logic app project. Backend is a python fastAPI project and frontend is a Next.js project.

**Comment by ccastrotrejo** [comment]
Hi @ppanchal-mobiz I took a look at it and we will be fixing it in this PR https://github.com/Azure/LogicAppsUX/pull/6536 Thanks for letting us know about it!
